language: node_js
node_js:
    - "7"
    - "8"
    - "9"
    - "10"
os:
    - linux
    - osx
matrix:
    exclude:
        - os: osx
          node_js: "9"
cache:
    directories:
        - node_modules
